Save iptables and ip6tables data separately
 - Added FIREHOL_AUTOSAVE6 to control ip6tables file
 - Moved file-detection logic to configure script
 - Use XML entities as a common means to set configure variables

Logic should detect Debian, RedHat, Gentoo and Arch. Use ./configure
parameters to override:
  --with-autosave=PATH    Use the PATH to save IPv4 rules to.
  --with-autosave6=PATH   Use the PATH to save IPv6 rules to.

diff --git a/sbin/firehol.in b/sbin/firehol.in
--- a/sbin/firehol.in
+++ b/sbin/firehol.in
@@ -857,9 +857,12 @@ test -z "$FIREHOL_ROUTING" && \
 	FIREHOL_ROUTING=0
 
 # Where /etc/init.d/iptables expects its configuration?
-# Leave it empty for automatic detection
 test -z "$FIREHOL_AUTOSAVE" && \
-	FIREHOL_AUTOSAVE=
+	set_or_def -n FIREHOL_AUTOSAVE "@FIREHOL_AUTOSAVE@" ""
+
+# Where /etc/init.d/iptables6 expects its configuration?
+test -z "$FIREHOL_AUTOSAVE6" && \
+	set_or_def -n FIREHOL_AUTOSAVE6 "@FIREHOL_AUTOSAVE6@" ""
 
 # Set to non-empty to wait (max 60 seconds) for a network interface
 test -z "$WAIT_FOR_IFACE" && \
@@ -7702,51 +7705,74 @@ fi
 
 if [ ${FIREHOL_SAVE} -eq 1 ]
 then
-	if [ -z "${FIREHOL_AUTOSAVE}" ]
+	save_status=0
+
+	if [ "$IPVER" = "ipv4" -o  "$IPVER" = "both" ]
 	then
-		if [ -d "/etc/sysconfig" ]
+		if [ -z "${FIREHOL_AUTOSAVE}" ]
 		then
-			# RedHat
-			FIREHOL_AUTOSAVE="/etc/sysconfig/iptables"
-		elif [ -d "/var/lib/iptables" ]
-		then
-			if [ -f /etc/conf.d/iptables ]
-			then
-				# Gentoo
-				IPTABLES_SAVE=
-				
-				. /etc/conf.d/iptables
-				FIREHOL_AUTOSAVE="${IPTABLES_SAVE}"
-			fi
-			
-			if [ -z "${FIREHOL_AUTOSAVE}" ]
-			then
-				# Debian
-				FIREHOL_AUTOSAVE="/var/lib/iptables/autosave"
-			fi
-		else
-			error "Cannot find where to save iptables file. Please set FIREHOL_AUTOSAVE."
+			error "No default location to save iptables file. Please set FIREHOL_AUTOSAVE."
 			echo
-			exit 1
+			save_status=1
 		fi
 	fi
-	
-	echo -n $"FireHOL: Saving firewall to ${FIREHOL_AUTOSAVE}:"
-	
-	fixed_iptables_save >"${FIREHOL_AUTOSAVE}"
-	
-	if [ ! $? -eq 0 ]
+
+	if [ "$IPVER" = "ipv6" -o  "$IPVER" = "both" ]
 	then
-		syslog err "Failed to save new firewall to '${FIREHOL_AUTOSAVE}'."
-		failure $"FireHOL: Saving firewall to ${FIREHOL_AUTOSAVE}:"
-		echo
-		exit 1
+		if [ -z "${FIREHOL_AUTOSAVE6}" ]
+		then
+			error "No default location to save ip6tables file. Please set FIREHOL_AUTOSAVE6."
+			echo
+			save_status=1
+		fi
 	fi
-	
-	syslog info "New firewall saved to '${FIREHOL_AUTOSAVE}'."
-	success $"FireHOL: Saving firewall to ${FIREHOL_AUTOSAVE}:"
-	echo
-	
+
+	if [ $save_status -ne 0 ]
+	then
+		exit $save_status
+	fi
+
+	if [ "$IPVER" = "ipv4" -o  "$IPVER" = "both" ]
+	then
+		echo -n $"FireHOL: Saving ipv4 firewall to ${FIREHOL_AUTOSAVE}:"
+		IPVER=ipv4 fixed_iptables_save >"${FIREHOL_AUTOSAVE}"
+
+		if [ ! $? -eq 0 ]
+		then
+			syslog err "Failed to save new ipv4 firewall to '${FIREHOL_AUTOSAVE}'."
+			failure $"FireHOL: Saving ipv4 firewall to ${FIREHOL_AUTOSAVE}:"
+			echo
+			save_status=1
+		fi
+
+		syslog info "New ipv4 firewall saved to '${FIREHOL_AUTOSAVE}'."
+		success $"FireHOL: Saving ipv4 firewall to ${FIREHOL_AUTOSAVE}:"
+		echo
+	fi
+
+	if [ "$IPVER" = "ipv6" -o  "$IPVER" = "both" ]
+	then
+		echo -n $"FireHOL: Saving ipv6 firewall to ${FIREHOL_AUTOSAVE6}:"
+		IPVER=ipv6 fixed_iptables_save >"${FIREHOL_AUTOSAVE6}"
+
+		if [ ! $? -eq 0 ]
+		then
+			syslog err "Failed to save new ipv6 firewall to '${FIREHOL_AUTOSAVE6}'."
+			failure $"FireHOL: Saving ipv6 firewall to ${FIREHOL_AUTOSAVE6}:"
+			echo
+			save_status=1
+		fi
+
+		syslog info "New ipv6 firewall saved to '${FIREHOL_AUTOSAVE6}'."
+		success $"FireHOL: Saving ipv6 firewall to ${FIREHOL_AUTOSAVE6}:"
+		echo
+	fi
+
+	if [ $save_status -ne 0 ]
+	then
+		exit $save_status
+	fi
+
 	# Save the list of modules we need to run to restore the firewall.
 	if [ -f "${FIREHOL_SPOOL_DIR}/last_save_modules.sh" ]
 	then
